// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: control.proto

#include "control.pb.h"
#include "control.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>

static const char* ControlService_method_names[] = {
  "/ControlService/ListenSetWRAM",
};

std::unique_ptr< ControlService::Stub> ControlService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControlService::Stub> stub(new ControlService::Stub(channel, options));
  return stub;
}

ControlService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ListenSetWRAM_(ControlService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::SetWRAM>* ControlService::Stub::ListenSetWRAMRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::SetWRAM>::Create(channel_.get(), rpcmethod_ListenSetWRAM_, context, request);
}

void ControlService::Stub::async::ListenSetWRAM(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::SetWRAM>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::SetWRAM>::Create(stub_->channel_.get(), stub_->rpcmethod_ListenSetWRAM_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::SetWRAM>* ControlService::Stub::AsyncListenSetWRAMRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::SetWRAM>::Create(channel_.get(), cq, rpcmethod_ListenSetWRAM_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::SetWRAM>* ControlService::Stub::PrepareAsyncListenSetWRAMRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::SetWRAM>::Create(channel_.get(), cq, rpcmethod_ListenSetWRAM_, context, request, false, nullptr);
}

ControlService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ControlService::Service, ::google::protobuf::Empty, ::SetWRAM>(
          [](ControlService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::SetWRAM>* writer) {
               return service->ListenSetWRAM(ctx, req, writer);
             }, this)));
}

ControlService::Service::~Service() {
}

::grpc::Status ControlService::Service::ListenSetWRAM(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::SetWRAM>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


