// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#include "control.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

PROTOBUF_CONSTEXPR SetWRAM::SetWRAM(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.bytes_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.bank_)*/0u
  , /*decltype(_impl_.byte_offset_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct SetWRAMDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetWRAMDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetWRAMDefaultTypeInternal() {}
  union {
    SetWRAM _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetWRAMDefaultTypeInternal _SetWRAM_default_instance_;
static ::_pb::Metadata file_level_metadata_control_2eproto[1];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_control_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_control_2eproto = nullptr;

const uint32_t TableStruct_control_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::SetWRAM, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::SetWRAM, _impl_.bank_),
  PROTOBUF_FIELD_OFFSET(::SetWRAM, _impl_.byte_offset_),
  PROTOBUF_FIELD_OFFSET(::SetWRAM, _impl_.bytes_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::SetWRAM)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::_SetWRAM_default_instance_._instance,
};

const char descriptor_table_protodef_control_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\rcontrol.proto\032\033google/protobuf/empty.p"
  "roto\";\n\007SetWRAM\022\014\n\004bank\030\001 \001(\r\022\023\n\013byte_of"
  "fset\030\002 \001(\r\022\r\n\005bytes\030\003 \001(\0142E\n\016ControlServ"
  "ice\0223\n\rListenSetWRAM\022\026.google.protobuf.E"
  "mpty\032\010.SetWRAM0\001b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_control_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::_pbi::once_flag descriptor_table_control_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_control_2eproto = {
    false, false, 184, descriptor_table_protodef_control_2eproto,
    "control.proto",
    &descriptor_table_control_2eproto_once, descriptor_table_control_2eproto_deps, 1, 1,
    schemas, file_default_instances, TableStruct_control_2eproto::offsets,
    file_level_metadata_control_2eproto, file_level_enum_descriptors_control_2eproto,
    file_level_service_descriptors_control_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_control_2eproto_getter() {
  return &descriptor_table_control_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_control_2eproto(&descriptor_table_control_2eproto);

// ===================================================================

class SetWRAM::_Internal {
 public:
};

SetWRAM::SetWRAM(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:SetWRAM)
}
SetWRAM::SetWRAM(const SetWRAM& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  SetWRAM* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.bytes_){}
    , decltype(_impl_.bank_){}
    , decltype(_impl_.byte_offset_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_bytes().empty()) {
    _this->_impl_.bytes_.Set(from._internal_bytes(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.bank_, &from._impl_.bank_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.byte_offset_) -
    reinterpret_cast<char*>(&_impl_.bank_)) + sizeof(_impl_.byte_offset_));
  // @@protoc_insertion_point(copy_constructor:SetWRAM)
}

inline void SetWRAM::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.bytes_){}
    , decltype(_impl_.bank_){0u}
    , decltype(_impl_.byte_offset_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.bytes_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.bytes_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

SetWRAM::~SetWRAM() {
  // @@protoc_insertion_point(destructor:SetWRAM)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void SetWRAM::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.bytes_.Destroy();
}

void SetWRAM::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void SetWRAM::Clear() {
// @@protoc_insertion_point(message_clear_start:SetWRAM)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.bytes_.ClearToEmpty();
  ::memset(&_impl_.bank_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.byte_offset_) -
      reinterpret_cast<char*>(&_impl_.bank_)) + sizeof(_impl_.byte_offset_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SetWRAM::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 bank = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.bank_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint32 byte_offset = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _impl_.byte_offset_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // bytes bytes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_bytes();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* SetWRAM::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:SetWRAM)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 bank = 1;
  if (this->_internal_bank() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_bank(), target);
  }

  // uint32 byte_offset = 2;
  if (this->_internal_byte_offset() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(2, this->_internal_byte_offset(), target);
  }

  // bytes bytes = 3;
  if (!this->_internal_bytes().empty()) {
    target = stream->WriteBytesMaybeAliased(
        3, this->_internal_bytes(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:SetWRAM)
  return target;
}

size_t SetWRAM::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:SetWRAM)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes bytes = 3;
  if (!this->_internal_bytes().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::BytesSize(
        this->_internal_bytes());
  }

  // uint32 bank = 1;
  if (this->_internal_bank() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_bank());
  }

  // uint32 byte_offset = 2;
  if (this->_internal_byte_offset() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_byte_offset());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData SetWRAM::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    SetWRAM::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*SetWRAM::GetClassData() const { return &_class_data_; }


void SetWRAM::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<SetWRAM*>(&to_msg);
  auto& from = static_cast<const SetWRAM&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:SetWRAM)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_bytes().empty()) {
    _this->_internal_set_bytes(from._internal_bytes());
  }
  if (from._internal_bank() != 0) {
    _this->_internal_set_bank(from._internal_bank());
  }
  if (from._internal_byte_offset() != 0) {
    _this->_internal_set_byte_offset(from._internal_byte_offset());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void SetWRAM::CopyFrom(const SetWRAM& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SetWRAM)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetWRAM::IsInitialized() const {
  return true;
}

void SetWRAM::InternalSwap(SetWRAM* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.bytes_, lhs_arena,
      &other->_impl_.bytes_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetWRAM, _impl_.byte_offset_)
      + sizeof(SetWRAM::_impl_.byte_offset_)
      - PROTOBUF_FIELD_OFFSET(SetWRAM, _impl_.bank_)>(
          reinterpret_cast<char*>(&_impl_.bank_),
          reinterpret_cast<char*>(&other->_impl_.bank_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SetWRAM::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_control_2eproto_getter, &descriptor_table_control_2eproto_once,
      file_level_metadata_control_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::SetWRAM*
Arena::CreateMaybeMessage< ::SetWRAM >(Arena* arena) {
  return Arena::CreateMessageInternal< ::SetWRAM >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
