// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_control_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_control_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/empty.pb.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_control_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_control_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_control_2eproto;
class SetWRAM;
struct SetWRAMDefaultTypeInternal;
extern SetWRAMDefaultTypeInternal _SetWRAM_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::SetWRAM* Arena::CreateMaybeMessage<::SetWRAM>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class SetWRAM final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SetWRAM) */ {
 public:
  inline SetWRAM() : SetWRAM(nullptr) {}
  ~SetWRAM() override;
  explicit PROTOBUF_CONSTEXPR SetWRAM(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetWRAM(const SetWRAM& from);
  SetWRAM(SetWRAM&& from) noexcept
    : SetWRAM() {
    *this = ::std::move(from);
  }

  inline SetWRAM& operator=(const SetWRAM& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetWRAM& operator=(SetWRAM&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetWRAM& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetWRAM* internal_default_instance() {
    return reinterpret_cast<const SetWRAM*>(
               &_SetWRAM_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SetWRAM& a, SetWRAM& b) {
    a.Swap(&b);
  }
  inline void Swap(SetWRAM* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetWRAM* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetWRAM* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetWRAM>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetWRAM& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetWRAM& from) {
    SetWRAM::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetWRAM* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SetWRAM";
  }
  protected:
  explicit SetWRAM(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBytesFieldNumber = 3,
    kBankFieldNumber = 1,
    kByteOffsetFieldNumber = 2,
  };
  // bytes bytes = 3;
  void clear_bytes();
  const std::string& bytes() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_bytes(ArgT0&& arg0, ArgT... args);
  std::string* mutable_bytes();
  PROTOBUF_NODISCARD std::string* release_bytes();
  void set_allocated_bytes(std::string* bytes);
  private:
  const std::string& _internal_bytes() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bytes(const std::string& value);
  std::string* _internal_mutable_bytes();
  public:

  // uint32 bank = 1;
  void clear_bank();
  uint32_t bank() const;
  void set_bank(uint32_t value);
  private:
  uint32_t _internal_bank() const;
  void _internal_set_bank(uint32_t value);
  public:

  // uint32 byte_offset = 2;
  void clear_byte_offset();
  uint32_t byte_offset() const;
  void set_byte_offset(uint32_t value);
  private:
  uint32_t _internal_byte_offset() const;
  void _internal_set_byte_offset(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SetWRAM)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr bytes_;
    uint32_t bank_;
    uint32_t byte_offset_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_control_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SetWRAM

// uint32 bank = 1;
inline void SetWRAM::clear_bank() {
  _impl_.bank_ = 0u;
}
inline uint32_t SetWRAM::_internal_bank() const {
  return _impl_.bank_;
}
inline uint32_t SetWRAM::bank() const {
  // @@protoc_insertion_point(field_get:SetWRAM.bank)
  return _internal_bank();
}
inline void SetWRAM::_internal_set_bank(uint32_t value) {
  
  _impl_.bank_ = value;
}
inline void SetWRAM::set_bank(uint32_t value) {
  _internal_set_bank(value);
  // @@protoc_insertion_point(field_set:SetWRAM.bank)
}

// uint32 byte_offset = 2;
inline void SetWRAM::clear_byte_offset() {
  _impl_.byte_offset_ = 0u;
}
inline uint32_t SetWRAM::_internal_byte_offset() const {
  return _impl_.byte_offset_;
}
inline uint32_t SetWRAM::byte_offset() const {
  // @@protoc_insertion_point(field_get:SetWRAM.byte_offset)
  return _internal_byte_offset();
}
inline void SetWRAM::_internal_set_byte_offset(uint32_t value) {
  
  _impl_.byte_offset_ = value;
}
inline void SetWRAM::set_byte_offset(uint32_t value) {
  _internal_set_byte_offset(value);
  // @@protoc_insertion_point(field_set:SetWRAM.byte_offset)
}

// bytes bytes = 3;
inline void SetWRAM::clear_bytes() {
  _impl_.bytes_.ClearToEmpty();
}
inline const std::string& SetWRAM::bytes() const {
  // @@protoc_insertion_point(field_get:SetWRAM.bytes)
  return _internal_bytes();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SetWRAM::set_bytes(ArgT0&& arg0, ArgT... args) {
 
 _impl_.bytes_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SetWRAM.bytes)
}
inline std::string* SetWRAM::mutable_bytes() {
  std::string* _s = _internal_mutable_bytes();
  // @@protoc_insertion_point(field_mutable:SetWRAM.bytes)
  return _s;
}
inline const std::string& SetWRAM::_internal_bytes() const {
  return _impl_.bytes_.Get();
}
inline void SetWRAM::_internal_set_bytes(const std::string& value) {
  
  _impl_.bytes_.Set(value, GetArenaForAllocation());
}
inline std::string* SetWRAM::_internal_mutable_bytes() {
  
  return _impl_.bytes_.Mutable(GetArenaForAllocation());
}
inline std::string* SetWRAM::release_bytes() {
  // @@protoc_insertion_point(field_release:SetWRAM.bytes)
  return _impl_.bytes_.Release();
}
inline void SetWRAM::set_allocated_bytes(std::string* bytes) {
  if (bytes != nullptr) {
    
  } else {
    
  }
  _impl_.bytes_.SetAllocated(bytes, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.bytes_.IsDefault()) {
    _impl_.bytes_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SetWRAM.bytes)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_control_2eproto
